server:
  port: 8080
  servlet:
    #context-path: /cil
  shutdown: graceful

---
application:
  name: SIGACIL
  domain:
    url: http://localhost:4200
  resources:
    static-locations: classpath:/static/

---
jwt:
  base64-secret: gy6FjjrA/lco3CQU3+KOyvdYSE4pE5p8qgSRckx+1aQoqAFmTVW7ZKoD7UWeg0WuAFEO7Xq+WEaSb4p/kk6jQg==
  # Token is valid 12 hours
  token-validity-in-seconds: 43200
  token-validity-in-seconds-for-remember-me: 259200
  token-confirm: 86400
  token-reset: 86400

---
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        show_sql: false
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
      additional-exclude: .h2.server.properties
    livereload:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/activite-cil
    username: postgres
    password: some
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enable: true
      path: /h2-console
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: devstgvap@gmail.com
    password: vbrvlbsmzxaeupqv
    test-connection: false
    properties:
      mail:
        smtp:
          ssl:
          trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true

---
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui: #pour trier les chemins d'API dans l'ordre de leurs méthodes HTTP
    operationsSorter: method

---
#log app
logging:
  level:
    ROOT: INFO
    cil.bf.activiteApp: 
      - DEBUG
      - INFO

---
storage:
  # replace 'localhost' by host address for production
  host: http://localhost:8080${server.servlet.context-path:/}
  folder: ${user.home}/storage/

